### ISSUE TITLE
Build failure related to C allocator

### ISSUE THREAD

**Issue by Morilli** [zackradisic/tether#1]
Hey, I was trying to build this using the provided makefile and ran into the following build error:
```
$ make
cd editor && zig build
/snap/zig/11625/lib/std/heap.zig:38:13: error: C allocator is only available when linking against libc
            @compileError("C allocator is only available when linking against libc");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/snap/zig/11625/lib/std/c/linux.zig:295:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn malloc_usable_size(?*const anyopaque) usize;
           ^~~
/snap/zig/11625/lib/std/c/linux.zig:294:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn posix_memalign(memptr: *?*anyopaque, alignment: usize, size: usize) c_int;
           ^~~
/snap/zig/11625/lib/std/c.zig:1732:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn free(?*anyopaque) void;
           ^~~
make: *** [Makefile:3: zig] Error 2
```

I tried this on both windows and (wsl) ubuntu, but both give the same error. My `zig version` is `0.13.0`.

**Comment by reidiens** [comment]
I get the same error. Might be something wrong in the build.zig file

**Comment by MARLENELASSEINPHOTOMACHEN** [comment]
To get the _current_ version to build with zig 0.13.0 you need to:

- clone repository recursively: (add --recurse-submodules): _using gh:_ `gh repo clone zackradisic/tether -- --recurse-submodules`
- -> make sure tether/editor/src/syntax includes both **tree-sitter-zig** and **tree-sitter-c**not just empty folders  - _I had to manually add both submodules (just get the repositories [zig](https://github.com/ziglibs/tree-sitter-zig) [c](https://github.com/tree-sitter/tree-sitter-c))_
- build.zig references **MacOSX13.3.sdk** (lines 152-154) so make sure they exist under the specified path - _I had installed 15.1.sdk only, so I just edited build.zig lines 152 - 154 to reference MacOSX15.1.sdk_
  
navigate to tether/editor and run `zig build`

**Comment by jason5122** [comment]
@MARLENELASSEINPHOTOMACHEN Thank you for the help! I was able to compile it without issue.

This seems to generate the `EditorKit.xcframework` file. I suspect this is for the Xcode project, so I load it up and run it. I get the following screen below:

<img width="864" alt="Screenshot 2024-11-05 at 4 48 21 PM" src="https://github.com/user-attachments/assets/651e3e78-7402-436e-a1e3-23b99867f724">

Do you know if this is it so far? Is there a way to demo the editor portion of the app?

**Comment by MARLENELASSEINPHOTOMACHEN** [comment]
Okay perfect, you're halfway there :) the editor will appear when focusing a textbox, e.g. TextEdit, and pressing **cmd** + **shift** + **space**
  
You will likely run into some issues:

- editor/src/**font.zig** at **line 533** creates a file at _/Users/zackradisic/Code/tether/editor/atlas.bin_:  
`533        var file = std.fs.createFileAbsolute("/Users/zackradisic/Code/tether/editor/atlas.bin", .{}) catch @panic("OOPS");  `
 change the path to wherever your `/tether/editor/` is located.  

- tether/**EditorView.swift** at **line 165** uses _.bgra8Unorm_srgb_ (while editor/src/hdr.zig line 15 doesnt): change 
`165        view.colorPixelFormat = .bgra8Unorm_srgb`  
to:
`165        view.colorPixelFormat = .bgra8Unorm`  

- same file  tether/**EditorView.swift** at **line 176**:
`176        let url = URL(fileURLWithPath: "/Users/zackradisic/Code/tether/atlas.png")`
change the path to your repository.

- editor/src/**font.zig** at **line 70** references **Rec Mono Linear**:
`70    const iosevka = metal.NSString.new_with_bytes("Rec Mono Linear", .ascii);`
change that to whatever font you have installed, or download and install [Recursive Mono Linear](https://www.recursive.design)

now you _should_ be good to go: rebuild in /editor/: `zig build` and start the Xcode project.
____
- _your xcode build might fail and prompt you to sign with your own team (just a click in the error msg)_
- _tether might need permission to listen to your keyboard -> System Settings > Privacy & Security > Accessibility > Enable tether_

**Comment by Musickiller** [comment]
> To get the _current_ version to build with zig 0.13.0 you need to:
> 
>     * clone repository recursively: (add --recurse-submodules): _using gh:_ `gh repo clone zackradisic/tether -- --recurse-submodules`

strange -- I always call "clone" with this flag, and the dirs are still empty.


>     * build.zig references **MacOSX13.3.sdk** (lines 152-154) so make sure they exist under the specified path - _I had installed 15.1.sdk only, so I just edited build.zig lines 152 - 154 to reference MacOSX15.1.sdk_

Does it only work on MacOS? Haven't seen that said anywhere(

> navigate to tether/editor and run `zig build`

Still the same error...

**Comment by scuttyrht** [comment]
> To get the _current_ version to build with zig 0.13.0 you need to:
> 
> * clone repository recursively: (add --recurse-submodules): _using gh:_ `gh repo clone zackradisic/tether -- --recurse-submodules`
> * -> make sure tether/editor/src/syntax includes both **tree-sitter-zig** and **tree-sitter-c** not just empty folders  - _I had to manually add both submodules (just get the repositories [zig](https://github.com/ziglibs/tree-sitter-zig) [c](https://github.com/tree-sitter/tree-sitter-c))_
> * build.zig references **MacOSX13.3.sdk** (lines 152-154) so make sure they exist under the specified path - _I had installed 15.1.sdk only, so I just edited build.zig lines 152 - 154 to reference MacOSX15.1.sdk_
> 
> navigate to tether/editor and run `zig build`

Do I just have to download and unzip the repositories for `tree-sitter-zig` and `tree-sitter-c` or do I have to use commands?

**Comment by reidiens** [comment]
> clone repository recursively: (add --recurse-submodules): using gh: gh repo clone zackradisic/tether -- --recurse-submodules

> make sure tether/editor/src/syntax includes both tree-sitter-zig and tree-sitter-c not just empty folders - I had to manually add both submodules (just get the repositories [zig](https://github.com/ziglibs/tree-sitter-zig) [c](https://github.com/tree-sitter/tree-sitter-c))

after doing this, I'm still unable to build. I keep getting the error 
```
/usr/lib/zig/std/heap.zig:38:13: error: C allocator is only available when linking against libc
            @compileError("C allocator is only available when linking against libc");

/usr/lib/zig/std/heap.zig:38:13: error: C allocator is only available when linking against libc
            @compileError("C allocator is only available when linking against libc");
```

**Comment by iQiexie** [comment]
> Okay perfect, you're halfway there :) the editor will appear when focusing a textbox, e.g. TextEdit, and pressing **cmd** + **shift** + **space**
> 
> You will likely run into some issues:
> 
> * editor/src/**font.zig** at **line 533** creates a file at _/Users/zackradisic/Code/tether/editor/atlas.bin_:
>   `533        var file = std.fs.createFileAbsolute("/Users/zackradisic/Code/tether/editor/atlas.bin", .{}) catch @panic("OOPS");  `
>   change the path to wherever your `/tether/editor/` is located.
> * tether/**EditorView.swift** at **line 165** uses _.bgra8Unorm_srgb_ (while editor/src/hdr.zig line 15 doesnt): change
>   `165        view.colorPixelFormat = .bgra8Unorm_srgb`
>   to:
>   `165        view.colorPixelFormat = .bgra8Unorm`
> * same file  tether/**EditorView.swift** at **line 176**:
>   `176        let url = URL(fileURLWithPath: "/Users/zackradisic/Code/tether/atlas.png")`
>   change the path to your repository.
> * editor/src/**font.zig** at **line 70** references **Rec Mono Linear**:
>   `70    const iosevka = metal.NSString.new_with_bytes("Rec Mono Linear", .ascii);`
>   change that to whatever font you have installed, or download and install [Recursive Mono Linear](https://www.recursive.design)
> 
> now you _should_ be good to go: rebuild in /editor/: `zig build` and start the Xcode project.
> 
> * _your xcode build might fail and prompt you to sign with your own team (just a click in the error msg)_
> * _tether might need permission to listen to your keyboard -> System Settings > Privacy & Security > Accessibility > Enable tether_

this window doesn't change. Maybe these errors in the console are the reason?

<img width="584" alt="image" src="https://github.com/user-attachments/assets/e4452a13-ef66-4bfd-823f-7222a3f60759">

**Comment by iQiexie** [comment]
I also tried to debug the app (i have written 0 lines of code in swift) and i places this prints in the start app

```
func start() {
        print("Started")
        //        mouseEventHandler = NSEvent.addGlobalMonitorForEvents(matching: .mouseMoved) { event in
        //            self.handleMouseMovement(event: event)
        //        }
        
        let keyModifierShiftCmdSpace: NSEvent.ModifierFlags = [.shift, .command]
        let keySpace: UInt16 = 49 // spacebar keycode
        
        //        let eventMask = NSEvent.EventTypeMask.flagsChanged.rawValue | NSEvent.EventTypeMask.keyDown.rawValue
        let eventMask = NSEvent.EventTypeMask.keyDown.rawValue
        print("Dispatching")
        
        
        DispatchQueue.main.async {
            self.keyDownEventHandler = NSEvent.addGlobalMonitorForEvents(matching: NSEvent.EventTypeMask(rawValue: eventMask)) {
                (event: NSEvent?) in
                guard let event = event else {
                    print("Returned ")
                    return
                }
                
                print("Keycode \(event.modifierFlags)")
                
                // on SHIFT + CMD + SPACE
                if event.modifierFlags.contains(keyModifierShiftCmdSpace) && event.keyCode == keySpace {
                    print("Keycode DONE DONEEE")
                    self.handleToggleTether(event: event)
                    return
                }
                
                print("Keycode \(event.keyCode)")
            }
        }
        
    }
```


i'm only getting 

```
Started
Dispatching
```

nothing more

**Comment by iQiexie** [comment]
Digging further I've noticed that I am getting `cannotComplete` (raw code is `-25204`) error when getting a focus of a window here

```
public extension AXUIElement {
    func get<Value>(_ attribute: AXAttribute, logErrors: Bool = true) throws -> Value? {
        precondition(Thread.isMainThread)
        var value: AnyObject?
        let code = AXUIElementCopyAttributeValue(self, attribute.rawValue as CFString, &value)
        if let error = AXError(code: code) {
            print("ERRRORRR!!!! \(error)")
            
            switch error {
            case .attributeUnsupported, .noValue, .cannotComplete:
                return nil
            default:
//                if logErrors {
//                    axLogger?.e(error, "get(\(attribute))")
//                }
                throw error
            }
        }
        return try unpack(value!) as? Value
    }
...
```

even though I added this app in the accessibility settings (even the debug binary)
